rust:
  - stable
  - beta
  - nightly

cache: cargo

install:
  - rustup component add llvm-tools-preview
  - rustup target add thumbv7em-none-eabihf

jobs:
  include:
    - stage: lint
      rust: stable
      cache: cargo
      install: rustup component add clippy
      script: cargo clippy --all

    - stage: format
      rust: stable
      install: rustup component add rustfmt
      script: cargo fmt --all -- --check
